services:
  crypto-tax-reporter:
    image: ghcr.io/gsp-p-77/crypto-tax-reporter:latest
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    restart: unless-stopped

