name: Build and Deploy (Restricted Mode)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # === Step 1: Checkout ===
      - name: Checkout repository
        run: |
          echo "Cloning repository..."
          git clone https://github.com/${{ github.repository }} .
          git fetch --all
          git checkout ${{ github.ref_name }}

      # === Step 2: Login to GitHub Container Registry ===
      - name: Login to GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # === Step 3: Build and push Docker image ===
      - name: Build and push Docker image
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          IMAGE=ghcr.io/${OWNER}/crypto-tax-reporter:latest
          echo "Building image: $IMAGE"
          docker build -t $IMAGE .
          docker push $IMAGE

      # === Step 4: Trigger Portainer webhook ===
      - name: Trigger Portainer redeploy
        env:
          PORTAINER_WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
        run: |
          echo "Triggering Portainer webhook..."
          curl -X POST "$PORTAINER_WEBHOOK_URL"
